syntax = "proto3";

package chats.v1;

import "google/protobuf/empty.proto";

service ChatsService {
  rpc CreateChat (CreateChatRequest) returns (CreateChatResponse);
  rpc UpdateChat (UpdateChatRequest) returns (google.protobuf.Empty);
  rpc DeleteChat (DeleteChatRequest) returns (google.protobuf.Empty);
  rpc GetChatById (GetChatByIdRequest) returns (GetChatByIdResponse);
  rpc GetChatsByName (GetChatsByNameRequest) returns (GetChatsByNameResponse);
  rpc AddMemberToChat (AddMemberToChatRequest) returns (google.protobuf.Empty);
  rpc RemoveMemberFromChat (RemoveMemberFromChatRequest) returns (google.protobuf.Empty);
  rpc ChangeRole (ChangeRoleRequest) returns (google.protobuf.Empty);
}

message CreateChatRequest {
  string actor_id    = 1;
  string name        = 2;
  string description = 3;
}

message CreateChatResponse {
  string id = 1;
}

message UpdateChatRequest {
  string          id          = 1;
  optional string name        = 2;
  optional string description = 3;
}

message DeleteChatRequest {
  string id       = 1;
  string actor_id = 2;
}

message GetChatByIdRequest {
  string id = 1;
}

message GetChatByIdResponse {
  ChatResponse chat = 1;
}

message GetChatsByNameRequest {
  string         name   = 1;
  optional int32 limit  = 2;
  optional int32 offset = 3;
}

message GetChatsByNameResponse {
  repeated ChatResponse chats = 1;
}

message ChatResponse {
  string                       id           = 1;
  string                       name         = 2;
  string                       description  = 3;
  repeated ParticipantResponse participants = 4;
}

message ParticipantResponse {
  string   user_id      = 1;
  string   login        = 2;
  string   display_name = 3;
  ChatRole role         = 4;
}

enum ChatRole {
  MEMBER = 0;
  ADMIN  = 1;
}

message AddMemberToChatRequest {
  string chat_id  = 1;
  string user_id  = 2;
  string actor_id = 3;
}

message RemoveMemberFromChatRequest {
  string chat_id  = 1;
  string user_id  = 2;
  string actor_id = 3;
}

message ChangeRoleRequest {
  string   chat_id  = 1;
  string   user_id  = 2;
  string   actor_id = 3;
  ChatRole role     = 4;
}